# App stack
CONFIG_MAIN_STACK_SIZE=16384

# C Library
# Default use minimal libc and with MINIMAL_LIBC_MALLOC_ARENA_SIZE defining
# HEAP size (512 bytes) are enought to run DNS.
CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE=16384
# C newlib
#CONFIG_NEWLIB_LIBC=y
#CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
#CONFIG_HEAP_MEM_POOL_SIZE=16384

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_SHELL=y

# Sockets
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
CONFIG_NET_SOCKETS_POLL_MAX=4

# Network driver config
CONFIG_TEST_RANDOM_GENERATOR=y

# Network address config
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_DHCPV4=y

# Resolver
CONFIG_DNS_RESOLVER=y

# HTTP
CONFIG_HTTP_CLIENT=y

# Network debug config
CONFIG_LOG=y
CONFIG_LOG_IMMEDIATE=y
CONFIG_NET_LOG=n
CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=n
CONFIG_NET_HTTP_LOG_LEVEL_DBG=n

# west build -b sam4e_xpro samples/net/sockets/tagoio_http_client -- -DCONF_FILE="prj.conf overlay-wifi.conf" -DSHIELD=esp_8266

# TagoIO API
CONFIG_TAGOIO_DEVICE_TOKEN="<your device token API>"
CONFIG_TAGOIO_HTTP_LOG_LEVEL_DBG=n
